In [30]:
import numpy as np


In [31]:
def train_hopfield(patterns):

    num_neurons = patterns.shape[1]
    W = np.zeros((num_neurons, num_neurons))

    for p in patterns:
        p = p.reshape(-1, 1)
        W += p @ p.T

    np.fill_diagonal(W, 0)
    return W


In [32]:
def hopfield_recall(W, pattern, steps=10):

    state = pattern.copy()

    for _ in range(steps):
        for i in range(len(state)):
            net_input = np.dot(W[i], state)
            state[i] = 1 if net_input >= 0 else -1

    return state


In [33]:
patterns = np.array([
    [ 1, -1,  1, -1],
    [-1,  1, -1,  1]
])


In [34]:
W = train_hopfield(patterns)

print("Weight Matrix:\n", W)


Weight Matrix:
 [[ 0. -2.  2. -2.]
 [-2.  0. -2.  2.]
 [ 2. -2.  0. -2.]
 [-2.  2. -2.  0.]]


In [35]:
# Noisy version of first pattern
noisy_pattern = np.array([1, -1, -1, -1])

print("\nOriginal Pattern: ", patterns[0])
print("Noisy Input:      ", noisy_pattern)

recalled = hopfield_recall(W, noisy_pattern)

print("Recalled Pattern: ", recalled)



Original Pattern:  [ 1 -1  1 -1]
Noisy Input:       [ 1 -1 -1 -1]
Recalled Pattern:  [ 1 -1  1 -1]
